/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a1ab0f28-551c-4d32-b1f6-da9406be32d4",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_MaSbDhz6F",
    "aws_user_pools_web_client_id": "62e2t5k9l7lekhoe8sghlvagsj",
    "oauth": {}
};


export default awsmobile;
